### ISSUE TITLE
Please update to opencv-python 4.0+

### ISSUE THREAD

**Issue by ryboe** [leblancfg/autocrop#106]
From `poetry`:
```toml
# pyproject.toml

[tool.poetry.dependencies]
python = "^3.8"
autocrop = "~1.0.2"
opencv-python = "~4.4.0"
```
```
[SolverProblemError]
Because autocrop (1.0.2) depends on opencv-python (>=3,<4)
 and no versions of autocrop match >1.0.2,<1.1.0, autocrop (>=1.0.2,<1.1.0) requires opencv-python (>=3,<4).
So, because backend depends on both autocrop (~1.0.2) and opencv-python (~4.4.0), version solving failed.
```

Anyone using `autocrop` is not able to use recent versions of `opencv-python`. Please update to `opencv-python` 4.0+ to unblock this. Thanks!
